FROM node:12.18.1 as build

# install chrome for tests
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
RUN apt-get update && apt-get install -yq google-chrome-stable

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

# copy the application files
COPY ./ActivitySignUpPortal .

# install npm packges
RUN npm install
RUN npm install -g @angular/cli@10.0.4


# run the tests
# RUN ng test --watch=false
# RUN ng e2e --port 4202

# generate build
RUN ng build --output-path=dist


###  PRODUCTION IMAGE
FROM nginx:1.16.0-alpine

# copy build output
COPY --from=build /app/dist /usr/share/nginx/html

#expose HTTP port
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]