version: "3.8"

services:
  client:
    image: acr.acnicholls.com/activity_client:latest
    networks:
      activity:
        aliases:
          - client
  api:
    image: acr.acnicholls.com/activity_api:latest
    links:
      - db
    networks:
      activity:
        aliases:
          - api
  db:
    image: acr.acnicholls.com/activity_db:latest
    networks:
      activity:
        aliases:
          - db
    volumes:
      - db_data:/var/opt/mssql/data:rw
  proxy:
    image: acr.acnicholls.com/activity_proxy:latest
    ports:
      - 80:80
    links:
      - client
      - api
    networks:
      activity:
        aliases:
          - proxy

networks:
  activity:

volumes:
  db_data:
