version: "3.8"

services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile.local
    image: activity_client:local
    volumes:
      - ./client/ActivitySignUpPortal:/app
    ports:
      - 3000:3000
    networks:
      activity:
        aliases:
          - client
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile.local
    image: activity_api:local
    links:
      - db
    ports:
      - 5000:5000
      - 5001:5001
    networks:
      activity:
        aliases:  
          - api    
  db:
    container_name: db
    build:
      context: ./db
      dockerfile: Dockerfile.local
    image: activity_db:local
    networks:
      activity:
        aliases:    
          - db
    volumes:
      - db_data:/var/opt/mssql/data:rw
  proxy:
    container_name: proxy
    build:
      context: ./proxy
      dockerfile: Dockerfile.local
    image: activity_proxy:local
    links:
      - client
      - api
    ports:
      - 80:80
    networks:
      activity:
        aliases:
          - proxy      

networks:
  activity:

volumes:
  db_data:
      