version: "3.9"

services:
  client:
    container_name: client
    build:
      context: ./client_react
      dockerfile: Dockerfile.dev
    image: activity_client:dev
    volumes:
      - ./client_react/activity-sign-up-portal:/app
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      activity:
        aliases:
          - client      
  proxy:
    container_name: proxy
    build:
      context: ./proxy
      dockerfile: Dockerfile.react
    image: activity_proxy:dev
    links:
      - client
    ports:
      - 80:80
    networks:
      activity:
        aliases:
          - proxy      
    
networks:
  activity: