FROM mcr.microsoft.com/mssql/server

ENV ACCEPT_EULA=Y
ARG SA_PASSWORD
ENV MSSQL_SA_PASSWORD=S3cur3P@ssw0rd
ENV MSSQL_PID=Developer

# copy sql backup
COPY ./ActivitySignUpDatabase.bak /tmp/ActivitySignUpDatabase.bak

# copy the create and restore script
COPY ./create_restore.sql /tmp/create_restore.sql

RUN (/opt/mssql/bin/sqlservr & ) | grep -q "Service Broker manager has started" && \
/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P S3cur3P@ssw0rd -i /tmp/create_restore.sql