FROM mcr.microsoft.com/mssql/server

ENV ACCEPT_EULA=Y
ENV MSSQL_SA_PASSWORD=S3cureP4ssW0rd

# copy sql backup
# COPY ./activity.bak /tmp/activity.bak

# copy the create and restore script
COPY ./create_db.sql /tmp/create_db.sql

RUN (/opt/mssql/bin/sqlservr & ) | grep -q "Service Broker manager has started" && \
/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P S3cureP4ssW0rd -i /tmp/create_db.sql