FROM mcr.microsoft.com/dotnet/sdk:3.1 as build-deps

WORKDIR /app

# copy the solution file
COPY . .

# restore nuget packages
RUN dotnet restore

RUN dotnet build -c Debug -o out

RUN mkdir /app/Resources
RUN mkdir /app/Resources/Images

ENV ASPNETCORE_ENVIRONMENT=Development

ENTRYPOINT ["dotnet", "ActivitySignUpApi.dll"]